# Generated by Django 5.2.7 on 2025-10-14 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier for the icon', max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(default='000000', max_length=20)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text="Title of the footer section, e.g., 'Company' or 'Support'", max_length=100)),
                ('section_type', models.CharField(choices=[('MAIN', 'Main Footer'), ('BOTTOM', 'Bottom Bar')], default='MAIN', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Optional text content, such as copyright notice or address', null=True)),
                ('link', models.CharField(blank=True, help_text='URL if this footer item is a link', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_social_link', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent section for grouped links', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CORE_APP.footermodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_items', to='CORE_APP.iconmodel')),
            ],
            options={
                'verbose_name': 'Footer Item',
                'verbose_name_plural': 'Footer Items',
                'ordering': ['section_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NavbarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(default='000000', max_length=20)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('font_family', models.CharField(default='Arial', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('show_icon', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_dropdown', models.BooleanField(default=False)),
                ('is_sticky', models.BooleanField(default=False)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('TOP', 'Top Navbar'), ('SIDE', 'Sidebar'), ('FOOTER', 'Footer Menu')], default='TOP', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navbar_items', to='CORE_APP.iconmodel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CORE_APP.navbarmodel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visible_to_roles', models.ManyToManyField(blank=True, to='auth.group')),
            ],
            options={
                'verbose_name': 'Navbar Item',
                'verbose_name_plural': 'Navbar Items',
                'ordering': ['position', 'order'],
            },
        ),
    ]
