# Generated by Django 5.2.7 on 2025-10-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footermodel',
            name='link',
        ),
        migrations.AddField(
            model_name='footermodel',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
