# Generated by Django 5.2.6 on 2025-09-17 10:38

import reader.models.DocumentModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "pdf",
                    models.FileField(
                        upload_to=reader.models.DocumentModel.upload_to_pdf
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=reader.models.DocumentModel.upload_to_audio,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
