# Generated by Django 5.2.6 on 2025-09-20 08:43

import reader.models.DocumentModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=reader.models.DocumentModel.upload_to_img,
            ),
        ),
    ]
