# Generated by Django 5.2.6 on 2025-09-22 06:44

import CORE_APP.utility.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PDF_APP", "0002_alter_pdfmodel_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfmodel",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="pdfmodel",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="pdfmodel",
            name="pdf_image",
        ),
        migrations.RemoveField(
            model_name="pdfmodel",
            name="video_file",
        ),
        migrations.AddField(
            model_name="pdfmodel",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=CORE_APP.utility.upload_path.upload_to_dir
            ),
        ),
        migrations.AddField(
            model_name="pdfmodel",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=CORE_APP.utility.upload_path.upload_to_dir
            ),
        ),
        migrations.AddField(
            model_name="pdfmodel",
            name="pdf",
            field=models.FileField(
                default="default.pdf", upload_to=CORE_APP.utility.upload_path.upload_to_dir
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdfmodel",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=CORE_APP.utility.upload_path.upload_to_dir
            ),
        ),
    ]
