# Generated by Django 5.2.6 on 2025-09-22 07:56

import CORE_APP.utility.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PDF_APP", "0004_alter_pdfmodel_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfmodel",
            name="extracted_text_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=CORE_APP.utility.upload_path.upload_to_dir,
            ),
        ),
    ]
