# Generated by Django 5.2.6 on 2025-09-21 13:54

import CORE_APP.utility.upload_path
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_damaged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to=CORE_APP.utility.upload_path.upload_to_pdf)),
                ('pdf_image', models.ImageField(upload_to=CORE_APP.utility.upload_path.upload_to_img)),
                ('extracted_text', models.TextField()),
                ('audio_file', models.FileField(upload_to=CORE_APP.utility.upload_path.upload_to_audio)),
                ('video_file', models.FileField(upload_to=CORE_APP.utility.upload_path.upload_to_video)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
