# Generated by Django 5.2.6 on 2025-09-21 14:33

import CORE_APP.utility.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDF_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=CORE_APP.utility.upload_path.upload_to_dir),
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=CORE_APP.utility.upload_path.upload_to_dir),
        ),
    ]
