# Generated by Django 5.2.6 on 2025-09-22 06:52

import CORE_APP.utility.upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "PDF_APP",
            "0003_remove_pdfmodel_audio_file_remove_pdfmodel_pdf_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfmodel",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=CORE_APP.utility.upload_path.upload_to_dir,
            ),
        ),
    ]
